# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.FloatField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Formula', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.FloatField()),
                ('Name', models.CharField(max_length=50)),
                ('Inier', models.IntegerField()),
                ('Val', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ierchem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField()),
                ('Minmax', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=150)),
                ('Abbr', models.CharField(max_length=50)),
                ('Razm', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ierin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.FloatField()),
                ('Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ierphy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.FloatField()),
                ('Name', models.CharField(max_length=150)),
                ('Razm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imgminer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.FloatField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Enname', models.CharField(max_length=50)),
                ('Ischange', models.IntegerField()),
                ('Prior', models.IntegerField()),
                ('Reiting', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.FloatField()),
                ('Name', models.CharField(max_length=50)),
                ('Val', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Physic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.FloatField()),
                ('Name', models.CharField(max_length=50)),
                ('Ier', models.FloatField()),
                ('Val', models.FloatField(null=True)),
            ],
        ),
    ]
